# Generated by Django 5.1.6 on 2025-03-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangocms_frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusItem',
            fields=[
            ],
            options={
                'verbose_name': 'PUI item',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
    ]
