# Generated by Django 3.0.5 on 2020-04-24 09:24

import cmsplus.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplus', '0001_initial'),
    ]

    operations = [
    ]
