# Generated by Django 2.2.12 on 2020-05-07 10:03

import cmsplus.models
import cmsplus.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplus', '0002_bootstrapimagepluginmodel_osmmarkermodel_textlinkpluginmodel'),
    ]

    operations = [
    ]
