# Generated by Django 5.2 on 2025-04-04 06:26

import cmsplus.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('cmsplus', '0005_slidepluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('_json', models.JSONField()),
            ],
            options={
                'verbose_name': 'Plus item',
            },
            bases=(cmsplus.models.PlusItemMixin, 'cms.cmsplugin'),
        ),
        migrations.DeleteModel(
            name='PlusPlugin',
        ),
    ]
