# Generated by Django 5.1.7 on 2025-03-27 20:28

import cmsplus.models
import djangocms_frontend.contrib.link.helpers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplus', '0005_slidepluginmodel'),
        ('djangocms_frontend', '0002_migrate_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusImage',
            fields=[
            ],
            options={
                'verbose_name': 'Plus Image',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(cmsplus.models.PlusItemMixin, djangocms_frontend.contrib.link.helpers.GetLinkMixin, 'djangocms_frontend.frontenduiitem'),
        ),
        migrations.CreateModel(
            name='PlusItem',
            fields=[
            ],
            options={
                'verbose_name': 'PUI item',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(cmsplus.models.PlusItemMixin, 'djangocms_frontend.frontenduiitem'),
        ),
        migrations.DeleteModel(
            name='PlusPlugin',
        ),
        migrations.CreateModel(
            name='PlusLinkedItem',
            fields=[
            ],
            options={
                'verbose_name': 'PUI item',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(djangocms_frontend.contrib.link.helpers.GetLinkMixin, 'cmsplus.plusitem'),
        ),
        migrations.CreateModel(
            name='SlidePluginModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cmsplus.pluslinkeditem',),
        ),
    ]
