# Generated by Django 5.2 on 2025-04-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplus', '0006_plusitem_delete_plusplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusImage',
            fields=[
            ],
            options={
                'verbose_name': 'Plus Image',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cmsplus.plusitem',),
        ),
    ]
